---
external_time:
  time_server:
    pool: # List of possible time pools
      - pool.ntp.org
  time_client:
    pool:
    server:

external_dns:
  dns_server: # set as forwarders in named.conf
    - 8.8.8.8
  dns_client: # set directly on client side in resolv.conf
